# Generated by Django 4.1.3 on 2022-11-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.IntegerField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(help_text='Enter the service name', max_length=150)),
            ],
            options={
                'ordering': ['service_name'],
            },
        ),
    ]
