# Generated by Django 4.1.3 on 2022-11-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_availability_availability_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='availability',
            name='slot_end',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='slot_start',
        ),
        migrations.AddField(
            model_name='availability',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
