# Generated by Django 4.1.3 on 2022-11-19 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_availability_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['date_time']},
        ),
        migrations.RemoveField(
            model_name='availability',
            name='date',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='time',
        ),
    ]
