# Generated by Django 4.1.3 on 2022-11-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_availability_options_remove_availability_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='availability',
            name='date_time',
        ),
        migrations.AddField(
            model_name='availability',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
