# Generated by Django 4.1.3 on 2022-11-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_availability_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
