# Generated by Django 4.1.3 on 2022-11-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_details_is_active_details_location_details_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='cancel_remarks',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
