# Generated by Django 4.1.3 on 2022-11-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_details_cancel_remarks_details_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='cancel_remarks',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
