# Generated by Django 4.1.3 on 2022-11-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_phonedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonedetails',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
