# Generated by Django 4.1.3 on 2022-11-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_alter_phonedetails_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonedetails',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
