# Generated by Django 4.1.3 on 2022-11-24 04:25

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_alter_phonedetails_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonedetails',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
