# Generated by Django 4.1.3 on 2022-11-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_alter_phonedetails_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
