# Generated by Django 4.1.3 on 2022-11-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_details_is_reminder_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PractitionerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practitioner_name', models.CharField(max_length=150)),
                ('service_id', models.IntegerField()),
            ],
            options={
                'ordering': ['practitioner_name'],
            },
        ),
    ]
