# Generated by Django 4.1.3 on 2022-11-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_practitionerdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='practitioner_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
