# Generated by Django 4.1.3 on 2022-12-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_practitionerdetails_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('no_of_cancels', models.IntegerField(default=0)),
                ('is_login_disabled', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
    ]
