# Generated by Django 4.1.3 on 2022-12-03 03:17

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_cancellationcontroller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonedetails',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128, region=None),
        ),
    ]
